name: Deloy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps: 
      - name: Checkout
        #uses: actions/checkout
        uses: actions/checkout@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag and Push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd store-app
          docker build -t $DOCKER_USER/store-app_example:$IMAGE_TAG .
          docker push $DOCKER_USER/store-app_example:$IMAGE_TAG
          echo "::set-output name=image::$DOCKER_USER/store-app_example:$IMAGE_TAG"

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      
      - name: Update Kubectl Context
        run: aws eks update-lubeconfig --name adorable-party-1692453467 --refion us-east-1
      
      - name: Deploy Image to AWS EKS
        run: |
          kubectl set image deployment/store store=${{ steps.build-image.outputs.image }}

